### ISSUE TITLE
Manifest output grouped by entry

### ISSUE THREAD

**Issue by knokit** [shonin/django-manifest-loader#19]
WebpackManifestPlugin allows using a custom [generate](https://github.com/shellscape/webpack-manifest-plugin#generate) function, which could be used to generate a manifest with the following structure:

``` javascript
{ "entryName": [ "runtime.js", "vendor.js", "entry.js"] }
```
With this structure it would be possible to get all files required to render a given entry and maybe it could also be used to determine the order by which the files should be imported (related to #3).

Possibly related to #14?

**Comment by shonin** [comment]
Thanks for the second report @knokit. Yes, one of my intentions behind #14 would be to allow structures like this. I will make sure this type of structure is possible when finishing up that PR

**Comment by knokit** [comment]
Great! Thanks a lot for your work, @shonin!
