### ISSUE TITLE
Support for Jinja2

### ISSUE THREAD

**Issue by rob101** [shonin/django-manifest-loader#21]
Is support planned for Jinja2 templates?

**Comment by shonin** [comment]
Hi @rob101, I hadn't previously considered it, however, after a bit of research, it doesn't look too difficult to port over. I should be able to work on it next week.

**Comment by shonin** [comment]
@rob101 if you or anyone else has an example of what you would consider a "standard" method of jinja2 installation in Django, and how that project installs external template tags like this that would make porting the code over a lot easier for me.

**Comment by rob101** [comment]
@shonin I think the best implementation is probably [https://niwinz.github.io/django-jinja](https://niwinz.github.io/django-jinja). The easiest way to install a template tag is perhaps to create a custom extension?

**Comment by rykener** [comment]
@rob101 thank you for the feature request. It has just been released in v1.0.0. Please find the documentation here: https://django-manifest-loader.readthedocs.io/en/stable/docs/usage.html#use-as-jinja-template-filter
