### ISSUE TITLE
Can't use a full URL as the file path

### ISSUE THREAD

**Issue by jkevingutierrez** [shonin/django-manifest-loader#23]
Despite #15 being closed, I'm not able to make it work using the latest django-manifest-loader 0.1.0 version.

Seems like the version in pypi wasn't updated with those changes https://pypi.org/project/django-manifest-loader/

It would be really useful to have a new version published with those updates

**Comment by jkevingutierrez** [comment]
Duplicated of #15

**Comment by shonin** [comment]
@jkevingutierrez thank you for this report. I just republished as v0.1.1 --- it looks like that resolved the issue. Please give it a shot and let me know. 

Best
