### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by shonin** [shonin/django-manifest-loader#27]
Documentation is currently subpar, and would benefit from attention. Goals are to write full docs with Sphinx to then host on Read the Docs. Anyone who wants to help is welcome to do so.

**Comment by ChristopherLandaverde** [comment]
Hey @shonin  I would love to help on this

**Comment by shonin** [comment]
hey @ChristopherLandaverde, great, any idea what you can contribute? Things that need to get done are

* Sphinx setup 
* convert the current readme into the bare-bones new documentation, which should be written in [`.rst`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)
* update the documentation to be more robust 
* proofreading 

if you had something else in mind that I didn't list feel free to let me know

**Comment by ChristopherLandaverde** [comment]
Hey @shonin 

So I will be working on converting the read me,  sphinx set up, and proofreading.

Do you mind if I continue to use? [.md](https://recommonmark.readthedocs.io/en/latest/) and would you be interested in adding docstrings?

**Comment by ChristopherLandaverde** [comment]
👍
